spring.application.name=Cafeteria

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/com_gammatech
spring.datasource.username=root
spring.datasource.password=M1987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server Configuration
server.error.include-message=always

# Bean Configuration
spring.main.allow-bean-definition-overriding=true
